name: tests-image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-png:
    name: PNG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make USE_HOSTED=1

      - name: Run PNG tests
        run: make test-png USE_HOSTED=1