name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: ubuntu-latest
            cc: clang
          - os: macos-latest
            cc: clang
          - os: windows-latest
            cc: gcc

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make CC=${{ matrix.cc }} USE_HOSTED=1
